apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "ortelius-docs.name" . }}
  labels:
  {{- range $key, $val := .Values.keptnLabels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ include "ortelius-docs.name" . }}
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app:  {{ include "ortelius-docs.name" . }}
        tier: backend
        track: stable
    spec:
      containers:
        - name: {{ include "ortelius-docs.name" . }}
          image: "{{ .Values.DockerRepo }}:{{ .Values.DockerTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80    
